// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn9j5u1K7Ih6YKwGA8Kx-yvgDwHUJL6TE',
    appId: '1:996921360023:web:0f080bb8e2e6a2ca1bf3d2',
    messagingSenderId: '996921360023',
    projectId: 'imtihon-4oy',
    authDomain: 'imtihon-4oy.firebaseapp.com',
    databaseURL: 'https://imtihon-4oy-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'imtihon-4oy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDGhMCB5gVvw70H12xiYoMs9B60IFwP8A',
    appId: '1:996921360023:android:595e1b69bbda08e31bf3d2',
    messagingSenderId: '996921360023',
    projectId: 'imtihon-4oy',
    databaseURL: 'https://imtihon-4oy-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'imtihon-4oy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtUdNxKYNj7taEoXR0jaAPnXv9EPDuKt8',
    appId: '1:996921360023:ios:d669b890b186bc5e1bf3d2',
    messagingSenderId: '996921360023',
    projectId: 'imtihon-4oy',
    databaseURL: 'https://imtihon-4oy-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'imtihon-4oy.appspot.com',
    iosBundleId: 'com.example.exam5Oy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtUdNxKYNj7taEoXR0jaAPnXv9EPDuKt8',
    appId: '1:996921360023:ios:d669b890b186bc5e1bf3d2',
    messagingSenderId: '996921360023',
    projectId: 'imtihon-4oy',
    databaseURL: 'https://imtihon-4oy-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'imtihon-4oy.appspot.com',
    iosBundleId: 'com.example.exam5Oy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn9j5u1K7Ih6YKwGA8Kx-yvgDwHUJL6TE',
    appId: '1:996921360023:web:87f12fdce53334901bf3d2',
    messagingSenderId: '996921360023',
    projectId: 'imtihon-4oy',
    authDomain: 'imtihon-4oy.firebaseapp.com',
    databaseURL: 'https://imtihon-4oy-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'imtihon-4oy.appspot.com',
  );
}
